language: c

sudo: false

os:
  - linux

# Trusty is necessary and Precise is unusable because the latter is missing
# libc 2.17 `libevent-2.1.so.5`.
dist: trusty

install:
  - cd ..
  - mkdir cortoproject
  - mv web cortoproject/web
  - cd cortoproject
  - git clone https://github.com/cortoproject/corto.git
  - git clone https://github.com/cortoproject/c-binding.git
  - git clone https://github.com/cortoproject/xml.git
  - git clone https://github.com/cortoproject/corto-language.git
  - git clone https://github.com/cortoproject/io.git
  - git clone https://github.com/cortoproject/cortodoc.git
  - git clone https://github.com/cortoproject/test.git
  - git clone https://github.com/cortoproject/json.git
  - |+
    echo 'COMPONENTS = %w(corto c-binding xml corto-language io cortodoc test json web)
    require "#{ENV["CORTO_BUILD"]}/forward"' > rakefile
  - for g in $(find . -name .git); do echo -e "$(basename $(dirname $g))\t$(git --git-dir $g rev-parse HEAD)"; done | column -t
  - source corto/configure
  - rake
  - cd web/server/test && rake && cd -

script:
  - cd web/server && corto test && cd -
